### ISSUE TITLE
Document module.hot.accept

### ISSUE THREAD

**Issue by quarterto** [AgentME/browserify-hmr#5]
If you're not coming from Webpack, there's no way of knowing this is needed.

**Comment by AgentME** [comment]
The readme has a link to the [hot module replacement API documentation](http://webpack.github.io/docs/hot-module-replacement.html).

I agree the readme needs a little more information on getting started with it. I expect that most people using hot module replacement are (or should be) using other tools to automatically apply or wrap around it, like [react-transform-hmr](https://github.com/gaearon/react-transform-hmr) and [ud](https://github.com/AgentME/ud), rather than using calls to `module.hot.*` themselves, so I don't want the readme to introduce people to hot module replacement by explaining the `module.hot.*` functions first. Because Webpack already has decent documentation on those functions, I'd rather link to them (also to help emphasize the fact that this project is compatible with code using those functions with Webpack).

**Comment by AgentME** [comment]
I've added a "Hot Module Replacement Usage" section to the readme which I hope functions as a better introduction to the plugin.

**Comment by quarterto** [comment]
That's great, thanks.
